version: '3.7'
services:
  app:
    image: node:10
    volumes:
      - ../cli:/app
    working_dir: /app
    command: /app/scripts/test.sh
    environment:
      - TEST_POSTGRES_URI=postgres://prisma:prisma@postgres/
    depends_on:
      - postgres
  postgres:
    image: postgres:10.3
    restart: always
    # ports:
    #   - '5432:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
  # mongo:
  #   image: mongo:3.6
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: prisma
  #     MONGO_INITDB_ROOT_PASSWORD: prisma
  #   ports:
  #     - '27018:27017'
  #   volumes:
  #     - mongo:/var/lib/mongo
  # mysql:
  #   image: mysql:5.7
  #   restart: always
  #   ports:
  #     - '3307:3306'
  #   environment:
  #     MYSQL_ROOT_PASSWORD: prisma
  #   volumes:
  #     - mysql:/var/lib/mysql

volumes:
  postgres:
  # ? mysql
  # ? mongo
