steps:
  - label: ':coverage: Test'
    plugins:
      - docker-compose:
          config: .buildkite/docker-compose.yml
          run: app
  - label: ':gun: Trigger publish'
    trigger: 'lift-publish'
    build:
      env:
        - PUBLISH_PRISMA2=false
