steps:
  - label: ':coverage: Test'
    plugins:
      - docker-compose:
          config: .buildkite/docker-compose.yml
          run: app
  - wait
  - label: ':gun: Trigger publish'
    trigger: 'lift-publish'
    async: true
    build:
      env:
        PUBLISH_PRISMA2: 'false'
