steps:
  - label: ':coverage: Test'
    plugins:
      - docker-compose#v3.0.3:
          config: .buildkite/docker-compose.yml
          run: app
  - wait
  - label: ':gun: publish @prisma/introspection & prisma2'
    trigger: 'prisma2-cli-publish'
    build:
      env:
        PUBLISH_INTROSPECTION: 'true'
        PUBLISH_PRISMA2: 'true'
