steps:
  - label: ':coverage: Test Prisma 2'
    trigger: 'prisma2-test'
  - label: ':flashlight: Publish Prisma 2'
    trigger: 'prisma2-publish'
    build:
      env:
        BUILDKITE_TAG: '${BUILDKITE_TAG}'

  - wait
